project_id = "asasikikrapixgznhmzl"

[functions.share-photo-url]
verify_jwt = false

[functions.share-export-url]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-transactional-email]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
