project_id = "asasikikrapixgznhmzl"

[functions.share-photo-url]
verify_jwt = false

[functions.share-logo-url]
verify_jwt = false

[functions.share-export-url]
verify_jwt = false

[functions.share-create-export]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-transactional-email]
verify_jwt = false

[functions.newsletter-signup]
verify_jwt = false

[functions.lead-magnet-signup]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
